### ISSUE TITLE
@styles/AppTheme is incompatible with attribute android:theme

### ISSUE THREAD

**Issue by FatCache** [oktadev/okta-android-example#1]
Trying to compile with targeted SDK version of 25 & `:appcompat-v7:25.3.1` but it wont compile.
```
\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:15: AAPT: error: '@styles/AppTheme' is incompatible with attribute android:theme (attr) reference.

error: failed processing manifest.
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.
```

**Comment by atticuslaurs** [comment]
Did you ever figure this out? I'm having the same issue

**Comment by arunk** [comment]
Tried searching for a while, finally gave in and installed the Android Studio. It should be '@style/AppTheme' not '@styles/AppTheme'.

**Comment by FatCache** [comment]
> Did you ever figure this out? I'm having the same issue

Sorry, I don't even remember. Closing.

**Comment by mathmul** [comment]
This worked for me: @style/MainTheme

**Comment by rezacse05** [comment]
Hi! I'm new in android app development. I'm facing the following problem. How can I sovle it.
AAPT: error: 'Style/Base.TextAppearance.Appcompat.Medium' is incompatible with attribute textAppearance (attr) reference.
